# Generated by Django 4.2.7 on 2023-12-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0017_remove_comentario_usuario_alter_comentario_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumento',
            options={'ordering': ['usuario', '-fechaPublicacion']},
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='instrumento',
            field=models.CharField(choices=[('guitarra', 'Guitarra')], default='guitarra', max_length=15),
        ),
    ]
