# Generated by Django 4.2.7 on 2023-12-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0020_rename_imageninstrumento_instrumento_imagenblog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='telefonoContacto',
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='instrumento',
            field=models.CharField(choices=[('guitarra', 'Guitarra')], default='guitarra', max_length=15),
        ),
    ]
