# Generated by Django 4.2.7 on 2023-12-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0021_remove_instrumento_telefonocontacto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumento',
            old_name='marca',
            new_name='subtitulo',
        ),
    ]
