# Generated by Django 4.2.7 on 2023-12-21 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0022_rename_marca_instrumento_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='emailContacto',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='precio',
        ),
    ]
