# Generated by Django 4.2.7 on 2023-12-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0023_remove_instrumento_emailcontacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='instrumento',
            field=models.CharField(choices=[('guitarra', 'Blog')], default='guitarra', max_length=15),
        ),
    ]
