# Generated by Django 4.2.7 on 2023-12-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0025_instrumento_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='direccion',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
