# Generated by Django 4.2.7 on 2023-12-22 07:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0027_alter_instrumento_direccion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instrumento',
            new_name='Blog',
        ),
    ]
